# Dockerfile.ci - volontairement degrade, support du TP4. Ne PAS deployer.
FROM node:24 AS installer
WORKDIR /juice-shop
COPY . /juice-shop
RUN npm install --omit=dev
RUN npm run build
# ENV JWT_SECRET=cn2VmHqPRq5FYd7hM8yTgKzXwLbEjA4s
# EXPOSE 3000
# CMD ["npm", "start"]

FROM  gcr.io/distroless/nodejs24-debian13
WORKDIR /juice-shop
COPY --from=installer --chown=65532:0 /juice-shop .
USER 65532
EXPOSE 300
CMD ["/juice-shop/build/app.js"]